package main

import (
	"encoding/json"
	"fmt"
	"net/http"
)

func mapbHandler(cfg *Config) error {

	if cfg.previous != "" {
		url = cfg.previous
	}

	var pokeresp AutoGenerated
	response, err := http.Get(url)
	if err != nil {
		return nil
	}

	json.NewDecoder(response.Body).Decode(&pokeresp)

	for _, result := range pokeresp.Results {
		fmt.Println(result.Name)
	}

	cfg.Next = pokeresp.Next
	cfg.previous = url
	return nil
}
