package main

import (
	"encoding/json"
	"fmt"
	"net/http"
)

var url = "https://pokeapi.co/api/v2/location-area/"

func mapHandler(cfg *Config) error {

	if cfg.Next != "" {
		url = cfg.Next
	}

	response, err := http.Get(url)
	if err != nil {
		return err
	}
	defer response.Body.Close()

	var pokeresp AutoGenerated
	err = json.NewDecoder(response.Body).Decode(&pokeresp)
	if err != nil {
		return err
	}

	for _, result := range pokeresp.Results {
		fmt.Println(result.Name)
	}

	cfg.Next = pokeresp.Next
	cfg.previous = url

	return nil
}
