package main

type AutoGenerated struct {
	Count    int      `json:"count"`
	Next     string   `json:"next"`
	Previous any      `json:"previous"`
	Results  []Result `json:"results"`
}

type Result struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}
